---
ansible_user: pirate

# For a 32-bit OS, set to 'arm'. For 64-bit OS, set to 'arm64'.
helm_arch: arm64

# Turing Pi.
# ingress_server_ip: 10.0.100.74
# load_balancer_server_ip: 10.0.100.99

# Dramble.
ingress_server_ip: 10.0.100.83
load_balancer_server_ip: 10.0.100.131
