---
- name: Deploy Prometheus Operator.
  k8s:
    definition: "{{ lookup('file', 'files/bundle.yaml') }}"
    state: present

- name: Deploy Prometheus.
  meta: noop

- name: Deploy Grafana.
  meta: noop
