---
- name: Deploy Prometheus Operator.
  k8s:
    definition: "{{ lookup('file', 'files/prometheus-operator.yaml') }}"
    state: present

- name: Wait for the servicemonitors CRD to be available.
  k8s_info:
    kind: servicemonitors
  register: servicemonitors_info
  until: servicemonitors_info['resources'] is defined
  retries: 10
  delay: 5

- name: Deploy Monitoring Resources.
  k8s:
    definition: "{{ lookup('file', 'files/' + item) }}"
    state: present
  loop:
    - node-exporter.yaml
    - prometheus.yaml
    # - alertmanager.yaml
    - grafana.yaml
  tags: ['dothis']
