---
- name: Set up cluster-wide configuration.
  hosts: k3s_cluster
  become: true

  roles:
    - role: node_exporter
      tags: ['monitoring', 'node_exporter']

- name: Deploy Kubernetes resources.
  hosts: master

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config

  pre_tasks:
    - name: Ensure required dependencies are installed.
      package:
        name: python3-setuptools
        state: present
      become: true
      tags: ['always']

    - name: Ensure openshift Python library is installed.
      pip:
        name: openshift
        state: present
      become: true
      tags: ['always']

  roles:
    - role: prometheus_kubernetes
      tags: ['monitoring', 'prometheus']

    - role: grafana_kubernetes
      tags: ['monitoring', 'grafana']
