---
# - name: Set up cluster-wide configuration.
#   hosts: k3s_cluster
#   become: true

#   tasks: []

- name: Deploy Kubernetes resources via master node.
  hosts: master
  gather_facts: false

  collections:
    - community.kubernetes

  vars:
    helm_arch: arm

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Ensure required dependencies are installed.
      package:
        name:
          - python3-setuptools
          - build-essential
          - golang
          - git
        state: present
      become: true

    - name: Ensure openshift Python library is installed.
      pip:
        name: openshift
        state: present
      become: true

  roles:
    - role: cluster_monitoring
      tags: ['monitoring', 'prometheus']

    - role: drupal
      tags: ['drupal']

    - role: wordpress
      tags: ['wordpress']

    - role: minecraft
      tags: ['minecraft']

    - role: pihole
      tags: ['pihole']
