---
- name: Create drupal namespace.
  k8s:
    name: drupal
    api_version: v1
    kind: Namespace
    state: present

- name: Apply drupal manifests.
  k8s:
    definition: "{{ lookup('file', 'files/' + item ) }}"
    state: present
  loop:
    - mariadb.yml
    - drupal.yml
